name: Run Desktop on Lambda Test

on:
  push:
    branches:
      - mobile_runs  # or any branch you want to trigger the workflow
  pull_request:
    branches:
      - mobile_runs  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: windows-latest  # Specifies the Windows runner

    steps:
      - uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up JDK 11  # Sets up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # AdoptOpenJDK's new project name

      - name: Run Desktop on Mobile
        run: |
          ./gradlew clean runDesktopOnLambdaTest "-PuserName=varunkumarb" "-PaccessKey=GhGShOYHz1jODWE9qDvkJK4nPDR3n2lc0gNp9VknalhwtUineG" "-Pplatform=ios" -Pbrowser=Safari "-PbrowserVersion=16.0" -Presolution=2560x1440 "-PrunName=Serenity Local"
        shell: bash  # Ensures the use of Bash shell even on Windows

      # Add any other steps here, such as caching dependencies
